project:
  type: website
  resources:
    - cv.pdf

website:
  favicon: avatar.jpg
  title: "Sukalpo Saha"
  site-url: "https://ahasoplakus.quarto.pub/kalpoverse/"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Hello!
        icon: person-raised-hand
      - href: work.qmd
        text: Work
        icon: laptop
      - href: personal.qmd
        text: Personal
        icon: person-badge
  
  page-footer:
    right: "This page is built with R and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Sukalpo Saha, 2025"

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    code-fold: true
    message: false
    warning: false

editor: visual

